git:
  depth: 5

language: c
compiler: gcc
os: linux
dist: xenial

addons:
  apt:
    packages:
    - libsnmp-dev
    - iptables-dev
    - libipset-dev
    - libnfnetlink-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libssl-dev
    - libmagic-dev
    - libglib2.0-dev
    - libjson-c-dev
    - libpcre2-dev
    - libmnl-dev
    - libnftnl-dev
    update: true

install:
  - autoreconf -W portability -visf

before_script:
  - ./test/ci/setup.sh

script:
  - ./test/ci/build.sh

env:
  matrix:
    - KEEPALIVED_CONFIG_ARGS=""
    - KEEPALIVED_CONFIG_ARGS="--enable-snmp --enable-snmp-rfc --enable-json --enable-dbus --disable-checksum-compat --enable-bfd --enable-asserts"
    - KEEPALIVED_CONFIG_ARGS="--enable-sha1 --enable-dbus --enable-dbus-create-instance --disable-dynamic-linking --disable-fwmark --disable-lvs-syncd --enable-snmp-vrrp --enable-timer-check --disable-iptables --disable-nftables --disable-track-process"
    - KEEPALIVED_CONFIG_ARGS="--enable-dynamic-linking --disable-vrrp-auth --enable-snmp-rfc --disable-snmp-reply-v3-for-v2 --disable-nftables"
    - KEEPALIVED_CONFIG_ARGS="--disable-libiptc --disable-libnl --enable-snmp-checker"
    - KEEPALIVED_CONFIG_ARGS="--enable-conversion-checks --enable-stacktrace --enable-mem-check --enable-mem-check-log --disable-lvs-64bit-stats --enable-snmp-rfcv2"
    - KEEPALIVED_CONFIG_ARGS="--disable-lvs --enable-snmp-vrrp --enable-snmp-rfc --enable-json --enable-sha1 --enable-dbus --disable-routes --enable-bfd --disable-iptables --disable-linkbeat"
    - KEEPALIVED_CONFIG_ARGS="--disable-vrrp --enable-snmp-checker --enable-sha1 --enable-regex"
    - KEEPALIVED_CONFIG_ARGS="--disable-hardening --enable-dump-threads --enable-epoll-debug --enable-snmp-rfcv3 --enable-log-file --disable-libipset"
