// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteDeviceNameAddrHandlerFunc turns a function with the right signature into a delete device name addr handler
type DeleteDeviceNameAddrHandlerFunc func(DeleteDeviceNameAddrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDeviceNameAddrHandlerFunc) Handle(params DeleteDeviceNameAddrParams) middleware.Responder {
	return fn(params)
}

// DeleteDeviceNameAddrHandler interface for that can handle valid delete device name addr params
type DeleteDeviceNameAddrHandler interface {
	Handle(DeleteDeviceNameAddrParams) middleware.Responder
}

// NewDeleteDeviceNameAddr creates a new http.Handler for the delete device name addr operation
func NewDeleteDeviceNameAddr(ctx *middleware.Context, handler DeleteDeviceNameAddrHandler) *DeleteDeviceNameAddr {
	return &DeleteDeviceNameAddr{Context: ctx, Handler: handler}
}

/*
	DeleteDeviceNameAddr swagger:route DELETE /device/{name}/addr device deleteDeviceNameAddr

delete special net device ip addr
*/
type DeleteDeviceNameAddr struct {
	Context *middleware.Context
	Handler DeleteDeviceNameAddrHandler
}

func (o *DeleteDeviceNameAddr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteDeviceNameAddrParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
