// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDeviceNameNetlinkAddrOKCode is the HTTP code returned for type DeleteDeviceNameNetlinkAddrOK
const DeleteDeviceNameNetlinkAddrOKCode int = 200

/*
DeleteDeviceNameNetlinkAddrOK Success

swagger:response deleteDeviceNameNetlinkAddrOK
*/
type DeleteDeviceNameNetlinkAddrOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDeviceNameNetlinkAddrOK creates DeleteDeviceNameNetlinkAddrOK with default headers values
func NewDeleteDeviceNameNetlinkAddrOK() *DeleteDeviceNameNetlinkAddrOK {

	return &DeleteDeviceNameNetlinkAddrOK{}
}

// WithPayload adds the payload to the delete device name netlink addr o k response
func (o *DeleteDeviceNameNetlinkAddrOK) WithPayload(payload string) *DeleteDeviceNameNetlinkAddrOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete device name netlink addr o k response
func (o *DeleteDeviceNameNetlinkAddrOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeviceNameNetlinkAddrOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteDeviceNameNetlinkAddrInternalServerErrorCode is the HTTP code returned for type DeleteDeviceNameNetlinkAddrInternalServerError
const DeleteDeviceNameNetlinkAddrInternalServerErrorCode int = 500

/*
DeleteDeviceNameNetlinkAddrInternalServerError Not Found

swagger:response deleteDeviceNameNetlinkAddrInternalServerError
*/
type DeleteDeviceNameNetlinkAddrInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDeviceNameNetlinkAddrInternalServerError creates DeleteDeviceNameNetlinkAddrInternalServerError with default headers values
func NewDeleteDeviceNameNetlinkAddrInternalServerError() *DeleteDeviceNameNetlinkAddrInternalServerError {

	return &DeleteDeviceNameNetlinkAddrInternalServerError{}
}

// WithPayload adds the payload to the delete device name netlink addr internal server error response
func (o *DeleteDeviceNameNetlinkAddrInternalServerError) WithPayload(payload string) *DeleteDeviceNameNetlinkAddrInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete device name netlink addr internal server error response
func (o *DeleteDeviceNameNetlinkAddrInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeviceNameNetlinkAddrInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
