// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteDeviceNameRouteHandlerFunc turns a function with the right signature into a delete device name route handler
type DeleteDeviceNameRouteHandlerFunc func(DeleteDeviceNameRouteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDeviceNameRouteHandlerFunc) Handle(params DeleteDeviceNameRouteParams) middleware.Responder {
	return fn(params)
}

// DeleteDeviceNameRouteHandler interface for that can handle valid delete device name route params
type DeleteDeviceNameRouteHandler interface {
	Handle(DeleteDeviceNameRouteParams) middleware.Responder
}

// NewDeleteDeviceNameRoute creates a new http.Handler for the delete device name route operation
func NewDeleteDeviceNameRoute(ctx *middleware.Context, handler DeleteDeviceNameRouteHandler) *DeleteDeviceNameRoute {
	return &DeleteDeviceNameRoute{Context: ctx, Handler: handler}
}

/*
	DeleteDeviceNameRoute swagger:route DELETE /device/{name}/route device deleteDeviceNameRoute

delete special net device route
*/
type DeleteDeviceNameRoute struct {
	Context *middleware.Context
	Handler DeleteDeviceNameRouteHandler
}

func (o *DeleteDeviceNameRoute) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteDeviceNameRouteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
