// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDeviceNameVlanOKCode is the HTTP code returned for type DeleteDeviceNameVlanOK
const DeleteDeviceNameVlanOKCode int = 200

/*
DeleteDeviceNameVlanOK Success

swagger:response deleteDeviceNameVlanOK
*/
type DeleteDeviceNameVlanOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDeviceNameVlanOK creates DeleteDeviceNameVlanOK with default headers values
func NewDeleteDeviceNameVlanOK() *DeleteDeviceNameVlanOK {

	return &DeleteDeviceNameVlanOK{}
}

// WithPayload adds the payload to the delete device name vlan o k response
func (o *DeleteDeviceNameVlanOK) WithPayload(payload string) *DeleteDeviceNameVlanOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete device name vlan o k response
func (o *DeleteDeviceNameVlanOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeviceNameVlanOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteDeviceNameVlanInternalServerErrorCode is the HTTP code returned for type DeleteDeviceNameVlanInternalServerError
const DeleteDeviceNameVlanInternalServerErrorCode int = 500

/*
DeleteDeviceNameVlanInternalServerError Failed

swagger:response deleteDeviceNameVlanInternalServerError
*/
type DeleteDeviceNameVlanInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteDeviceNameVlanInternalServerError creates DeleteDeviceNameVlanInternalServerError with default headers values
func NewDeleteDeviceNameVlanInternalServerError() *DeleteDeviceNameVlanInternalServerError {

	return &DeleteDeviceNameVlanInternalServerError{}
}

// WithPayload adds the payload to the delete device name vlan internal server error response
func (o *DeleteDeviceNameVlanInternalServerError) WithPayload(payload string) *DeleteDeviceNameVlanInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete device name vlan internal server error response
func (o *DeleteDeviceNameVlanInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteDeviceNameVlanInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
