// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteDeviceNameVlanHandlerFunc turns a function with the right signature into a delete device name vlan handler
type DeleteDeviceNameVlanHandlerFunc func(DeleteDeviceNameVlanParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDeviceNameVlanHandlerFunc) Handle(params DeleteDeviceNameVlanParams) middleware.Responder {
	return fn(params)
}

// DeleteDeviceNameVlanHandler interface for that can handle valid delete device name vlan params
type DeleteDeviceNameVlanHandler interface {
	Handle(DeleteDeviceNameVlanParams) middleware.Responder
}

// NewDeleteDeviceNameVlan creates a new http.Handler for the delete device name vlan operation
func NewDeleteDeviceNameVlan(ctx *middleware.Context, handler DeleteDeviceNameVlanHandler) *DeleteDeviceNameVlan {
	return &DeleteDeviceNameVlan{Context: ctx, Handler: handler}
}

/*
	DeleteDeviceNameVlan swagger:route DELETE /device/{name}/vlan device deleteDeviceNameVlan

delete special net device
*/
type DeleteDeviceNameVlan struct {
	Context *middleware.Context
	Handler DeleteDeviceNameVlanHandler
}

func (o *DeleteDeviceNameVlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteDeviceNameVlanParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
