// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDeviceNameAddrHandlerFunc turns a function with the right signature into a get device name addr handler
type GetDeviceNameAddrHandlerFunc func(GetDeviceNameAddrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDeviceNameAddrHandlerFunc) Handle(params GetDeviceNameAddrParams) middleware.Responder {
	return fn(params)
}

// GetDeviceNameAddrHandler interface for that can handle valid get device name addr params
type GetDeviceNameAddrHandler interface {
	Handle(GetDeviceNameAddrParams) middleware.Responder
}

// NewGetDeviceNameAddr creates a new http.Handler for the get device name addr operation
func NewGetDeviceNameAddr(ctx *middleware.Context, handler GetDeviceNameAddrHandler) *GetDeviceNameAddr {
	return &GetDeviceNameAddr{Context: ctx, Handler: handler}
}

/*
	GetDeviceNameAddr swagger:route GET /device/{name}/addr device getDeviceNameAddr

display special net device ip addr
*/
type GetDeviceNameAddr struct {
	Context *middleware.Context
	Handler GetDeviceNameAddrHandler
}

func (o *GetDeviceNameAddr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDeviceNameAddrParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
