// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDeviceNameVlanHandlerFunc turns a function with the right signature into a get device name vlan handler
type GetDeviceNameVlanHandlerFunc func(GetDeviceNameVlanParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDeviceNameVlanHandlerFunc) Handle(params GetDeviceNameVlanParams) middleware.Responder {
	return fn(params)
}

// GetDeviceNameVlanHandler interface for that can handle valid get device name vlan params
type GetDeviceNameVlanHandler interface {
	Handle(GetDeviceNameVlanParams) middleware.Responder
}

// NewGetDeviceNameVlan creates a new http.Handler for the get device name vlan operation
func NewGetDeviceNameVlan(ctx *middleware.Context, handler GetDeviceNameVlanHandler) *GetDeviceNameVlan {
	return &GetDeviceNameVlan{Context: ctx, Handler: handler}
}

/*
	GetDeviceNameVlan swagger:route GET /device/{name}/vlan device getDeviceNameVlan

display all net device list
*/
type GetDeviceNameVlan struct {
	Context *middleware.Context
	Handler GetDeviceNameVlanHandler
}

func (o *GetDeviceNameVlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDeviceNameVlanParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
