// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutDeviceNameAddrOKCode is the HTTP code returned for type PutDeviceNameAddrOK
const PutDeviceNameAddrOKCode int = 200

/*
PutDeviceNameAddrOK Update exist ip addr Success

swagger:response putDeviceNameAddrOK
*/
type PutDeviceNameAddrOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameAddrOK creates PutDeviceNameAddrOK with default headers values
func NewPutDeviceNameAddrOK() *PutDeviceNameAddrOK {

	return &PutDeviceNameAddrOK{}
}

// WithPayload adds the payload to the put device name addr o k response
func (o *PutDeviceNameAddrOK) WithPayload(payload string) *PutDeviceNameAddrOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name addr o k response
func (o *PutDeviceNameAddrOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameAddrOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutDeviceNameAddrCreatedCode is the HTTP code returned for type PutDeviceNameAddrCreated
const PutDeviceNameAddrCreatedCode int = 201

/*
PutDeviceNameAddrCreated Add new ip addr Success

swagger:response putDeviceNameAddrCreated
*/
type PutDeviceNameAddrCreated struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameAddrCreated creates PutDeviceNameAddrCreated with default headers values
func NewPutDeviceNameAddrCreated() *PutDeviceNameAddrCreated {

	return &PutDeviceNameAddrCreated{}
}

// WithPayload adds the payload to the put device name addr created response
func (o *PutDeviceNameAddrCreated) WithPayload(payload string) *PutDeviceNameAddrCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name addr created response
func (o *PutDeviceNameAddrCreated) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameAddrCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutDeviceNameAddrInternalServerErrorCode is the HTTP code returned for type PutDeviceNameAddrInternalServerError
const PutDeviceNameAddrInternalServerErrorCode int = 500

/*
PutDeviceNameAddrInternalServerError Failed

swagger:response putDeviceNameAddrInternalServerError
*/
type PutDeviceNameAddrInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameAddrInternalServerError creates PutDeviceNameAddrInternalServerError with default headers values
func NewPutDeviceNameAddrInternalServerError() *PutDeviceNameAddrInternalServerError {

	return &PutDeviceNameAddrInternalServerError{}
}

// WithPayload adds the payload to the put device name addr internal server error response
func (o *PutDeviceNameAddrInternalServerError) WithPayload(payload string) *PutDeviceNameAddrInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name addr internal server error response
func (o *PutDeviceNameAddrInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameAddrInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
