// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutDeviceNameNetlinkOKCode is the HTTP code returned for type PutDeviceNameNetlinkOK
const PutDeviceNameNetlinkOKCode int = 200

/*
PutDeviceNameNetlinkOK Success

swagger:response putDeviceNameNetlinkOK
*/
type PutDeviceNameNetlinkOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameNetlinkOK creates PutDeviceNameNetlinkOK with default headers values
func NewPutDeviceNameNetlinkOK() *PutDeviceNameNetlinkOK {

	return &PutDeviceNameNetlinkOK{}
}

// WithPayload adds the payload to the put device name netlink o k response
func (o *PutDeviceNameNetlinkOK) WithPayload(payload string) *PutDeviceNameNetlinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name netlink o k response
func (o *PutDeviceNameNetlinkOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameNetlinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutDeviceNameNetlinkInternalServerErrorCode is the HTTP code returned for type PutDeviceNameNetlinkInternalServerError
const PutDeviceNameNetlinkInternalServerErrorCode int = 500

/*
PutDeviceNameNetlinkInternalServerError Not Found

swagger:response putDeviceNameNetlinkInternalServerError
*/
type PutDeviceNameNetlinkInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameNetlinkInternalServerError creates PutDeviceNameNetlinkInternalServerError with default headers values
func NewPutDeviceNameNetlinkInternalServerError() *PutDeviceNameNetlinkInternalServerError {

	return &PutDeviceNameNetlinkInternalServerError{}
}

// WithPayload adds the payload to the put device name netlink internal server error response
func (o *PutDeviceNameNetlinkInternalServerError) WithPayload(payload string) *PutDeviceNameNetlinkInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name netlink internal server error response
func (o *PutDeviceNameNetlinkInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameNetlinkInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
