// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutDeviceNameNetlinkAddrHandlerFunc turns a function with the right signature into a put device name netlink addr handler
type PutDeviceNameNetlinkAddrHandlerFunc func(PutDeviceNameNetlinkAddrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutDeviceNameNetlinkAddrHandlerFunc) Handle(params PutDeviceNameNetlinkAddrParams) middleware.Responder {
	return fn(params)
}

// PutDeviceNameNetlinkAddrHandler interface for that can handle valid put device name netlink addr params
type PutDeviceNameNetlinkAddrHandler interface {
	Handle(PutDeviceNameNetlinkAddrParams) middleware.Responder
}

// NewPutDeviceNameNetlinkAddr creates a new http.Handler for the put device name netlink addr operation
func NewPutDeviceNameNetlinkAddr(ctx *middleware.Context, handler PutDeviceNameNetlinkAddrHandler) *PutDeviceNameNetlinkAddr {
	return &PutDeviceNameNetlinkAddr{Context: ctx, Handler: handler}
}

/*
	PutDeviceNameNetlinkAddr swagger:route PUT /device/{name}/netlink/addr device putDeviceNameNetlinkAddr

ip addr add 10.0.0.1/32 dev eth0: Set ip cird to linux net device
*/
type PutDeviceNameNetlinkAddr struct {
	Context *middleware.Context
	Handler PutDeviceNameNetlinkAddrHandler
}

func (o *PutDeviceNameNetlinkAddr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutDeviceNameNetlinkAddrParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
