// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutDeviceNameRouteHandlerFunc turns a function with the right signature into a put device name route handler
type PutDeviceNameRouteHandlerFunc func(PutDeviceNameRouteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutDeviceNameRouteHandlerFunc) Handle(params PutDeviceNameRouteParams) middleware.Responder {
	return fn(params)
}

// PutDeviceNameRouteHandler interface for that can handle valid put device name route params
type PutDeviceNameRouteHandler interface {
	Handle(PutDeviceNameRouteParams) middleware.Responder
}

// NewPutDeviceNameRoute creates a new http.Handler for the put device name route operation
func NewPutDeviceNameRoute(ctx *middleware.Context, handler PutDeviceNameRouteHandler) *PutDeviceNameRoute {
	return &PutDeviceNameRoute{Context: ctx, Handler: handler}
}

/*
	PutDeviceNameRoute swagger:route PUT /device/{name}/route device putDeviceNameRoute

add/update special net device route
*/
type PutDeviceNameRoute struct {
	Context *middleware.Context
	Handler PutDeviceNameRouteHandler
}

func (o *PutDeviceNameRoute) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutDeviceNameRouteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
