// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutDeviceNameRouteOKCode is the HTTP code returned for type PutDeviceNameRouteOK
const PutDeviceNameRouteOKCode int = 200

/*
PutDeviceNameRouteOK Update exist route Success

swagger:response putDeviceNameRouteOK
*/
type PutDeviceNameRouteOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameRouteOK creates PutDeviceNameRouteOK with default headers values
func NewPutDeviceNameRouteOK() *PutDeviceNameRouteOK {

	return &PutDeviceNameRouteOK{}
}

// WithPayload adds the payload to the put device name route o k response
func (o *PutDeviceNameRouteOK) WithPayload(payload string) *PutDeviceNameRouteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name route o k response
func (o *PutDeviceNameRouteOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameRouteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutDeviceNameRouteCreatedCode is the HTTP code returned for type PutDeviceNameRouteCreated
const PutDeviceNameRouteCreatedCode int = 201

/*
PutDeviceNameRouteCreated Add new route Success

swagger:response putDeviceNameRouteCreated
*/
type PutDeviceNameRouteCreated struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameRouteCreated creates PutDeviceNameRouteCreated with default headers values
func NewPutDeviceNameRouteCreated() *PutDeviceNameRouteCreated {

	return &PutDeviceNameRouteCreated{}
}

// WithPayload adds the payload to the put device name route created response
func (o *PutDeviceNameRouteCreated) WithPayload(payload string) *PutDeviceNameRouteCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name route created response
func (o *PutDeviceNameRouteCreated) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameRouteCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PutDeviceNameRouteInternalServerErrorCode is the HTTP code returned for type PutDeviceNameRouteInternalServerError
const PutDeviceNameRouteInternalServerErrorCode int = 500

/*
PutDeviceNameRouteInternalServerError Failed

swagger:response putDeviceNameRouteInternalServerError
*/
type PutDeviceNameRouteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutDeviceNameRouteInternalServerError creates PutDeviceNameRouteInternalServerError with default headers values
func NewPutDeviceNameRouteInternalServerError() *PutDeviceNameRouteInternalServerError {

	return &PutDeviceNameRouteInternalServerError{}
}

// WithPayload adds the payload to the put device name route internal server error response
func (o *PutDeviceNameRouteInternalServerError) WithPayload(payload string) *PutDeviceNameRouteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put device name route internal server error response
func (o *PutDeviceNameRouteInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutDeviceNameRouteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
