// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"

	"github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"github.com/dpvs-agent/restapi"
	"github.com/dpvs-agent/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!
func main() {
	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewDpvsAgentAPI(swaggerSpec)

	agent := &DpvsAgentServer{}

	parser := flags.NewParser(agent, flags.Default)
	parser.ShortDescription = "dpvs agent"
	parser.LongDescription = "dpvs agent api"
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server := agent.InstantiateServer(api)
	defer server.Shutdown()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
