// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dpvs-agent/models"
)

// DeleteVsVipPortOKCode is the HTTP code returned for type DeleteVsVipPortOK
const DeleteVsVipPortOKCode int = 200

/*
DeleteVsVipPortOK Success

swagger:response deleteVsVipPortOK
*/
type DeleteVsVipPortOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteVsVipPortOK creates DeleteVsVipPortOK with default headers values
func NewDeleteVsVipPortOK() *DeleteVsVipPortOK {

	return &DeleteVsVipPortOK{}
}

// WithPayload adds the payload to the delete vs vip port o k response
func (o *DeleteVsVipPortOK) WithPayload(payload string) *DeleteVsVipPortOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vs vip port o k response
func (o *DeleteVsVipPortOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVsVipPortOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteVsVipPortNotFoundCode is the HTTP code returned for type DeleteVsVipPortNotFound
const DeleteVsVipPortNotFoundCode int = 404

/*
DeleteVsVipPortNotFound Service not found

swagger:response deleteVsVipPortNotFound
*/
type DeleteVsVipPortNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteVsVipPortNotFound creates DeleteVsVipPortNotFound with default headers values
func NewDeleteVsVipPortNotFound() *DeleteVsVipPortNotFound {

	return &DeleteVsVipPortNotFound{}
}

// WithPayload adds the payload to the delete vs vip port not found response
func (o *DeleteVsVipPortNotFound) WithPayload(payload string) *DeleteVsVipPortNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vs vip port not found response
func (o *DeleteVsVipPortNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVsVipPortNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteVsVipPortFailureCode is the HTTP code returned for type DeleteVsVipPortFailure
const DeleteVsVipPortFailureCode int = 500

/*
DeleteVsVipPortFailure Service deletion failed

swagger:response deleteVsVipPortFailure
*/
type DeleteVsVipPortFailure struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewDeleteVsVipPortFailure creates DeleteVsVipPortFailure with default headers values
func NewDeleteVsVipPortFailure() *DeleteVsVipPortFailure {

	return &DeleteVsVipPortFailure{}
}

// WithPayload adds the payload to the delete vs vip port failure response
func (o *DeleteVsVipPortFailure) WithPayload(payload models.Error) *DeleteVsVipPortFailure {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete vs vip port failure response
func (o *DeleteVsVipPortFailure) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteVsVipPortFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
