// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteVsVipPortDenyHandlerFunc turns a function with the right signature into a delete vs vip port deny handler
type DeleteVsVipPortDenyHandlerFunc func(DeleteVsVipPortDenyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteVsVipPortDenyHandlerFunc) Handle(params DeleteVsVipPortDenyParams) middleware.Responder {
	return fn(params)
}

// DeleteVsVipPortDenyHandler interface for that can handle valid delete vs vip port deny params
type DeleteVsVipPortDenyHandler interface {
	Handle(DeleteVsVipPortDenyParams) middleware.Responder
}

// NewDeleteVsVipPortDeny creates a new http.Handler for the delete vs vip port deny operation
func NewDeleteVsVipPortDeny(ctx *middleware.Context, handler DeleteVsVipPortDenyHandler) *DeleteVsVipPortDeny {
	return &DeleteVsVipPortDeny{Context: ctx, Handler: handler}
}

/*
	DeleteVsVipPortDeny swagger:route DELETE /vs/{VipPort}/deny virtualserver deleteVsVipPortDeny

Delete a set of ip form black list to vip:port:proto
*/
type DeleteVsVipPortDeny struct {
	Context *middleware.Context
	Handler DeleteVsVipPortDenyHandler
}

func (o *DeleteVsVipPortDeny) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteVsVipPortDenyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
