// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteVsVipPortAllowHandlerFunc turns a function with the right signature into a delete vs vip port allow handler
type DeleteVsVipPortAllowHandlerFunc func(DeleteVsVipPortAllowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteVsVipPortAllowHandlerFunc) Handle(params DeleteVsVipPortAllowParams) middleware.Responder {
	return fn(params)
}

// DeleteVsVipPortAllowHandler interface for that can handle valid delete vs vip port allow params
type DeleteVsVipPortAllowHandler interface {
	Handle(DeleteVsVipPortAllowParams) middleware.Responder
}

// NewDeleteVsVipPortAllow creates a new http.Handler for the delete vs vip port allow operation
func NewDeleteVsVipPortAllow(ctx *middleware.Context, handler DeleteVsVipPortAllowHandler) *DeleteVsVipPortAllow {
	return &DeleteVsVipPortAllow{Context: ctx, Handler: handler}
}

/*
	DeleteVsVipPortAllow swagger:route DELETE /vs/{VipPort}/allow virtualserver deleteVsVipPortAllow

Delete a set of ip form white list to vip:port:proto
*/
type DeleteVsVipPortAllow struct {
	Context *middleware.Context
	Handler DeleteVsVipPortAllowHandler
}

func (o *DeleteVsVipPortAllow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteVsVipPortAllowParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
