// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteVsVipPortLaddrHandlerFunc turns a function with the right signature into a delete vs vip port laddr handler
type DeleteVsVipPortLaddrHandlerFunc func(DeleteVsVipPortLaddrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteVsVipPortLaddrHandlerFunc) Handle(params DeleteVsVipPortLaddrParams) middleware.Responder {
	return fn(params)
}

// DeleteVsVipPortLaddrHandler interface for that can handle valid delete vs vip port laddr params
type DeleteVsVipPortLaddrHandler interface {
	Handle(DeleteVsVipPortLaddrParams) middleware.Responder
}

// NewDeleteVsVipPortLaddr creates a new http.Handler for the delete vs vip port laddr operation
func NewDeleteVsVipPortLaddr(ctx *middleware.Context, handler DeleteVsVipPortLaddrHandler) *DeleteVsVipPortLaddr {
	return &DeleteVsVipPortLaddr{Context: ctx, Handler: handler}
}

/*
	DeleteVsVipPortLaddr swagger:route DELETE /vs/{VipPort}/laddr virtualserver deleteVsVipPortLaddr

DeleteVsVipPortLaddr delete vs vip port laddr API
*/
type DeleteVsVipPortLaddr struct {
	Context *middleware.Context
	Handler DeleteVsVipPortLaddrHandler
}

func (o *DeleteVsVipPortLaddr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteVsVipPortLaddrParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
