// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteVsVipPortRsHandlerFunc turns a function with the right signature into a delete vs vip port rs handler
type DeleteVsVipPortRsHandlerFunc func(DeleteVsVipPortRsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteVsVipPortRsHandlerFunc) Handle(params DeleteVsVipPortRsParams) middleware.Responder {
	return fn(params)
}

// DeleteVsVipPortRsHandler interface for that can handle valid delete vs vip port rs params
type DeleteVsVipPortRsHandler interface {
	Handle(DeleteVsVipPortRsParams) middleware.Responder
}

// NewDeleteVsVipPortRs creates a new http.Handler for the delete vs vip port rs operation
func NewDeleteVsVipPortRs(ctx *middleware.Context, handler DeleteVsVipPortRsHandler) *DeleteVsVipPortRs {
	return &DeleteVsVipPortRs{Context: ctx, Handler: handler}
}

/*
	DeleteVsVipPortRs swagger:route DELETE /vs/{VipPort}/rs virtualserver deleteVsVipPortRs

Delete a set of real server from vip:port:proto
*/
type DeleteVsVipPortRs struct {
	Context *middleware.Context
	Handler DeleteVsVipPortRsHandler
}

func (o *DeleteVsVipPortRs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteVsVipPortRsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
