// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVsVipPortDenyHandlerFunc turns a function with the right signature into a get vs vip port deny handler
type GetVsVipPortDenyHandlerFunc func(GetVsVipPortDenyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVsVipPortDenyHandlerFunc) Handle(params GetVsVipPortDenyParams) middleware.Responder {
	return fn(params)
}

// GetVsVipPortDenyHandler interface for that can handle valid get vs vip port deny params
type GetVsVipPortDenyHandler interface {
	Handle(GetVsVipPortDenyParams) middleware.Responder
}

// NewGetVsVipPortDeny creates a new http.Handler for the get vs vip port deny operation
func NewGetVsVipPortDeny(ctx *middleware.Context, handler GetVsVipPortDenyHandler) *GetVsVipPortDeny {
	return &GetVsVipPortDeny{Context: ctx, Handler: handler}
}

/*
	GetVsVipPortDeny swagger:route GET /vs/{VipPort}/deny virtualserver getVsVipPortDeny

GetVsVipPortDeny get vs vip port deny API
*/
type GetVsVipPortDeny struct {
	Context *middleware.Context
	Handler GetVsVipPortDenyHandler
}

func (o *GetVsVipPortDeny) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVsVipPortDenyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
