// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVsVipPortAllowHandlerFunc turns a function with the right signature into a get vs vip port allow handler
type GetVsVipPortAllowHandlerFunc func(GetVsVipPortAllowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVsVipPortAllowHandlerFunc) Handle(params GetVsVipPortAllowParams) middleware.Responder {
	return fn(params)
}

// GetVsVipPortAllowHandler interface for that can handle valid get vs vip port allow params
type GetVsVipPortAllowHandler interface {
	Handle(GetVsVipPortAllowParams) middleware.Responder
}

// NewGetVsVipPortAllow creates a new http.Handler for the get vs vip port allow operation
func NewGetVsVipPortAllow(ctx *middleware.Context, handler GetVsVipPortAllowHandler) *GetVsVipPortAllow {
	return &GetVsVipPortAllow{Context: ctx, Handler: handler}
}

/*
	GetVsVipPortAllow swagger:route GET /vs/{VipPort}/allow virtualserver getVsVipPortAllow

GetVsVipPortAllow get vs vip port allow API
*/
type GetVsVipPortAllow struct {
	Context *middleware.Context
	Handler GetVsVipPortAllowHandler
}

func (o *GetVsVipPortAllow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVsVipPortAllowParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
