// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dpvs-agent/models"
)

// GetVsOKCode is the HTTP code returned for type GetVsOK
const GetVsOKCode int = 200

/*
GetVsOK Success

swagger:response getVsOK
*/
type GetVsOK struct {

	/*
	  In: Body
	*/
	Payload *models.VirtualServerList `json:"body,omitempty"`
}

// NewGetVsOK creates GetVsOK with default headers values
func NewGetVsOK() *GetVsOK {

	return &GetVsOK{}
}

// WithPayload adds the payload to the get vs o k response
func (o *GetVsOK) WithPayload(payload *models.VirtualServerList) *GetVsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vs o k response
func (o *GetVsOK) SetPayload(payload *models.VirtualServerList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetVsNoContentCode is the HTTP code returned for type GetVsNoContent
const GetVsNoContentCode int = 204

/*
GetVsNoContent No Content

swagger:response getVsNoContent
*/
type GetVsNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.VirtualServerList `json:"body,omitempty"`
}

// NewGetVsNoContent creates GetVsNoContent with default headers values
func NewGetVsNoContent() *GetVsNoContent {

	return &GetVsNoContent{}
}

// WithPayload adds the payload to the get vs no content response
func (o *GetVsNoContent) WithPayload(payload *models.VirtualServerList) *GetVsNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vs no content response
func (o *GetVsNoContent) SetPayload(payload *models.VirtualServerList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
