// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVsHandlerFunc turns a function with the right signature into a get vs handler
type GetVsHandlerFunc func(GetVsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVsHandlerFunc) Handle(params GetVsParams) middleware.Responder {
	return fn(params)
}

// GetVsHandler interface for that can handle valid get vs params
type GetVsHandler interface {
	Handle(GetVsParams) middleware.Responder
}

// NewGetVs creates a new http.Handler for the get vs operation
func NewGetVs(ctx *middleware.Context, handler GetVsHandler) *GetVs {
	return &GetVs{Context: ctx, Handler: handler}
}

/*
	GetVs swagger:route GET /vs virtualserver getVs

display all vip:port:proto and rsip:port list
*/
type GetVs struct {
	Context *middleware.Context
	Handler GetVsHandler
}

func (o *GetVs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
