// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVsVipPortRsHandlerFunc turns a function with the right signature into a get vs vip port rs handler
type GetVsVipPortRsHandlerFunc func(GetVsVipPortRsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVsVipPortRsHandlerFunc) Handle(params GetVsVipPortRsParams) middleware.Responder {
	return fn(params)
}

// GetVsVipPortRsHandler interface for that can handle valid get vs vip port rs params
type GetVsVipPortRsHandler interface {
	Handle(GetVsVipPortRsParams) middleware.Responder
}

// NewGetVsVipPortRs creates a new http.Handler for the get vs vip port rs operation
func NewGetVsVipPortRs(ctx *middleware.Context, handler GetVsVipPortRsHandler) *GetVsVipPortRs {
	return &GetVsVipPortRs{Context: ctx, Handler: handler}
}

/*
	GetVsVipPortRs swagger:route GET /vs/{VipPort}/rs virtualserver getVsVipPortRs

GetVsVipPortRs get vs vip port rs API
*/
type GetVsVipPortRs struct {
	Context *middleware.Context
	Handler GetVsVipPortRsHandler
}

func (o *GetVsVipPortRs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVsVipPortRsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
