// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVsVipPortLaddrHandlerFunc turns a function with the right signature into a get vs vip port laddr handler
type GetVsVipPortLaddrHandlerFunc func(GetVsVipPortLaddrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVsVipPortLaddrHandlerFunc) Handle(params GetVsVipPortLaddrParams) middleware.Responder {
	return fn(params)
}

// GetVsVipPortLaddrHandler interface for that can handle valid get vs vip port laddr params
type GetVsVipPortLaddrHandler interface {
	Handle(GetVsVipPortLaddrParams) middleware.Responder
}

// NewGetVsVipPortLaddr creates a new http.Handler for the get vs vip port laddr operation
func NewGetVsVipPortLaddr(ctx *middleware.Context, handler GetVsVipPortLaddrHandler) *GetVsVipPortLaddr {
	return &GetVsVipPortLaddr{Context: ctx, Handler: handler}
}

/*
	GetVsVipPortLaddr swagger:route GET /vs/{VipPort}/laddr virtualserver getVsVipPortLaddr

GetVsVipPortLaddr get vs vip port laddr API
*/
type GetVsVipPortLaddr struct {
	Context *middleware.Context
	Handler GetVsVipPortLaddrHandler
}

func (o *GetVsVipPortLaddr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVsVipPortLaddrParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
