// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutVsVipPortHandlerFunc turns a function with the right signature into a put vs vip port handler
type PutVsVipPortHandlerFunc func(PutVsVipPortParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutVsVipPortHandlerFunc) Handle(params PutVsVipPortParams) middleware.Responder {
	return fn(params)
}

// PutVsVipPortHandler interface for that can handle valid put vs vip port params
type PutVsVipPortHandler interface {
	Handle(PutVsVipPortParams) middleware.Responder
}

// NewPutVsVipPort creates a new http.Handler for the put vs vip port operation
func NewPutVsVipPort(ctx *middleware.Context, handler PutVsVipPortHandler) *PutVsVipPort {
	return &PutVsVipPort{Context: ctx, Handler: handler}
}

/*
	PutVsVipPort swagger:route PUT /vs/{VipPort} virtualserver putVsVipPort

create or update virtual server
*/
type PutVsVipPort struct {
	Context *middleware.Context
	Handler PutVsVipPortHandler
}

func (o *PutVsVipPort) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutVsVipPortParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
