// Code generated by go-swagger; DO NOT EDIT.

package virtualserver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutVsVipPortLaddrHandlerFunc turns a function with the right signature into a put vs vip port laddr handler
type PutVsVipPortLaddrHandlerFunc func(PutVsVipPortLaddrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutVsVipPortLaddrHandlerFunc) Handle(params PutVsVipPortLaddrParams) middleware.Responder {
	return fn(params)
}

// PutVsVipPortLaddrHandler interface for that can handle valid put vs vip port laddr params
type PutVsVipPortLaddrHandler interface {
	Handle(PutVsVipPortLaddrParams) middleware.Responder
}

// NewPutVsVipPortLaddr creates a new http.Handler for the put vs vip port laddr operation
func NewPutVsVipPortLaddr(ctx *middleware.Context, handler PutVsVipPortLaddrHandler) *PutVsVipPortLaddr {
	return &PutVsVipPortLaddr{Context: ctx, Handler: handler}
}

/*
	PutVsVipPortLaddr swagger:route PUT /vs/{VipPort}/laddr virtualserver putVsVipPortLaddr

PutVsVipPortLaddr put vs vip port laddr API
*/
type PutVsVipPortLaddr struct {
	Context *middleware.Context
	Handler PutVsVipPortLaddrHandler
}

func (o *PutVsVipPortLaddr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutVsVipPortLaddrParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
