//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 IQiYi Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package comm

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealServer) DeepCopyInto(out *RealServer) {
	*out = *in
	in.Addr.DeepCopyInto(&out.Addr)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealServer.
func (in *RealServer) DeepCopy() *RealServer {
	if in == nil {
		return nil
	}
	out := new(RealServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualServer) DeepCopyInto(out *VirtualServer) {
	*out = *in
	in.Addr.DeepCopyInto(&out.Addr)
	if in.RSs != nil {
		in, out := &in.RSs, &out.RSs
		*out = make([]RealServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualServer.
func (in *VirtualServer) DeepCopy() *VirtualServer {
	if in == nil {
		return nil
	}
	out := new(VirtualServer)
	in.DeepCopyInto(out)
	return out
}
