.\"
.\"     ipvsadm-save(8) manual page
.\"     Inspired by ipchains-save
.\"
.\"	$Id$	
.\"
.\"     Authors: Wensong Zhang <wensong@linuxvirtualserver.org>
.\"
.\"     Changes:
.\"
.\"
.TH IPVSADM-SAVE 8 "22nd March 2001" "LVS Administration" "Linux Administrator's Guide"
.SH NAME
ipvsadm\-save \- save the IPVS table to stdout
.SH SYNOPSIS
.BR "ipvsadm\-save " [ -n ]
.SH DESCRIPTION
ipvsadm\-save prints the IPVS table to stdout.
.SH OPTIONS
The option that is recognized by
.B ipvsadm-save
is:
.TP
.BR -n
print out the table in numeric format.
.SH SEE ALSO
ipvsadm(8), the LVS\-HOWTO.
