.\"
.\"     ipvsadm-restore(8) manual page
.\"     Inspired by ipchains-restore
.\"
.\"	$Id$	
.\"
.\"     Authors: Wensong Zhang <wensong@linuxvirtualserver.org>
.\"
.\"     Changes:
.\"
.\"
.TH IPVSADM-RESTORE 8 "22nd March 2001" "LVS Administration" "Linux Administrator's Guide"
.SH NAME
ipvsadm\-restore \- restore the IPVS table from stdin
.SH SYNOPSIS
.BR "ipvsadm\-restore "
.SH DESCRIPTION
ipvsadm\-restore prints the IPVS table from stdin.
.SH OPTIONS
No options now.
.SH SEE ALSO
ipvsadm(8), the LVS\-HOWTO.
