// Code generated by go-swagger; DO NOT EDIT.

package ipset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddMemberOKCode is the HTTP code returned for type AddMemberOK
const AddMemberOKCode int = 200

/*
AddMemberOK Existed

swagger:response addMemberOK
*/
type AddMemberOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddMemberOK creates AddMemberOK with default headers values
func NewAddMemberOK() *AddMemberOK {

	return &AddMemberOK{}
}

// WithPayload adds the payload to the add member o k response
func (o *AddMemberOK) WithPayload(payload string) *AddMemberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add member o k response
func (o *AddMemberOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddMemberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AddMemberCreatedCode is the HTTP code returned for type AddMemberCreated
const AddMemberCreatedCode int = 201

/*
AddMemberCreated Created

swagger:response addMemberCreated
*/
type AddMemberCreated struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddMemberCreated creates AddMemberCreated with default headers values
func NewAddMemberCreated() *AddMemberCreated {

	return &AddMemberCreated{}
}

// WithPayload adds the payload to the add member created response
func (o *AddMemberCreated) WithPayload(payload string) *AddMemberCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add member created response
func (o *AddMemberCreated) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddMemberCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AddMemberBadRequestCode is the HTTP code returned for type AddMemberBadRequest
const AddMemberBadRequestCode int = 400

/*
AddMemberBadRequest Invalid ipset parameter

swagger:response addMemberBadRequest
*/
type AddMemberBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddMemberBadRequest creates AddMemberBadRequest with default headers values
func NewAddMemberBadRequest() *AddMemberBadRequest {

	return &AddMemberBadRequest{}
}

// WithPayload adds the payload to the add member bad request response
func (o *AddMemberBadRequest) WithPayload(payload string) *AddMemberBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add member bad request response
func (o *AddMemberBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddMemberBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AddMemberNotFoundCode is the HTTP code returned for type AddMemberNotFound
const AddMemberNotFoundCode int = 404

/*
AddMemberNotFound Ipset not found

swagger:response addMemberNotFound
*/
type AddMemberNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddMemberNotFound creates AddMemberNotFound with default headers values
func NewAddMemberNotFound() *AddMemberNotFound {

	return &AddMemberNotFound{}
}

// WithPayload adds the payload to the add member not found response
func (o *AddMemberNotFound) WithPayload(payload string) *AddMemberNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add member not found response
func (o *AddMemberNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddMemberNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AddMemberFailureCode is the HTTP code returned for type AddMemberFailure
const AddMemberFailureCode int = 500

/*
AddMemberFailure Service not available

swagger:response addMemberFailure
*/
type AddMemberFailure struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddMemberFailure creates AddMemberFailure with default headers values
func NewAddMemberFailure() *AddMemberFailure {

	return &AddMemberFailure{}
}

// WithPayload adds the payload to the add member failure response
func (o *AddMemberFailure) WithPayload(payload string) *AddMemberFailure {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add member failure response
func (o *AddMemberFailure) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddMemberFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
