// Code generated by go-swagger; DO NOT EDIT.

package ipset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddMemberHandlerFunc turns a function with the right signature into a add member handler
type AddMemberHandlerFunc func(AddMemberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddMemberHandlerFunc) Handle(params AddMemberParams) middleware.Responder {
	return fn(params)
}

// AddMemberHandler interface for that can handle valid add member params
type AddMemberHandler interface {
	Handle(AddMemberParams) middleware.Responder
}

// NewAddMember creates a new http.Handler for the add member operation
func NewAddMember(ctx *middleware.Context, handler AddMemberHandler) *AddMember {
	return &AddMember{Context: ctx, Handler: handler}
}

/*
	AddMember swagger:route POST /ipset/{name}/member ipset addMember

Add members to the ipset.
*/
type AddMember struct {
	Context *middleware.Context
	Handler AddMemberHandler
}

func (o *AddMember) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddMemberParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
