// Code generated by go-swagger; DO NOT EDIT.

package ipset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DelMemberHandlerFunc turns a function with the right signature into a del member handler
type DelMemberHandlerFunc func(DelMemberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DelMemberHandlerFunc) Handle(params DelMemberParams) middleware.Responder {
	return fn(params)
}

// DelMemberHandler interface for that can handle valid del member params
type DelMemberHandler interface {
	Handle(DelMemberParams) middleware.Responder
}

// NewDelMember creates a new http.Handler for the del member operation
func NewDelMember(ctx *middleware.Context, handler DelMemberHandler) *DelMember {
	return &DelMember{Context: ctx, Handler: handler}
}

/*
	DelMember swagger:route DELETE /ipset/{name}/member ipset delMember

Delete members from the ipset.
*/
type DelMember struct {
	Context *middleware.Context
	Handler DelMemberHandler
}

func (o *DelMember) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDelMemberParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
