// Code generated by go-swagger; DO NOT EDIT.

package ipset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAllHandlerFunc turns a function with the right signature into a get all handler
type GetAllHandlerFunc func(GetAllParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllHandlerFunc) Handle(params GetAllParams) middleware.Responder {
	return fn(params)
}

// GetAllHandler interface for that can handle valid get all params
type GetAllHandler interface {
	Handle(GetAllParams) middleware.Responder
}

// NewGetAll creates a new http.Handler for the get all operation
func NewGetAll(ctx *middleware.Context, handler GetAllHandler) *GetAll {
	return &GetAll{Context: ctx, Handler: handler}
}

/*
	GetAll swagger:route GET /ipset ipset getAll

Get all the ipsets and members.
*/
type GetAll struct {
	Context *middleware.Context
	Handler GetAllHandler
}

func (o *GetAll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAllParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
