// Code generated by go-swagger; DO NOT EDIT.

package ipset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IsInHandlerFunc turns a function with the right signature into a is in handler
type IsInHandlerFunc func(IsInParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IsInHandlerFunc) Handle(params IsInParams) middleware.Responder {
	return fn(params)
}

// IsInHandler interface for that can handle valid is in params
type IsInHandler interface {
	Handle(IsInParams) middleware.Responder
}

// NewIsIn creates a new http.Handler for the is in operation
func NewIsIn(ctx *middleware.Context, handler IsInHandler) *IsIn {
	return &IsIn{Context: ctx, Handler: handler}
}

/*
	IsIn swagger:route POST /ipset/{name}/cell ipset isIn

Check if an object in the ipset.
*/
type IsIn struct {
	Context *middleware.Context
	Handler IsInHandler
}

func (o *IsIn) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIsInParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// IsInOKBody is in o k body
//
// swagger:model IsInOKBody
type IsInOKBody struct {

	// message
	Message string `json:"Message,omitempty"`

	// result
	// Required: true
	Result *bool `json:"Result"`
}

// Validate validates this is in o k body
func (o *IsInOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IsInOKBody) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("isInOK"+"."+"Result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this is in o k body based on context it is used
func (o *IsInOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *IsInOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IsInOKBody) UnmarshalBinary(b []byte) error {
	var res IsInOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
