// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddrRange addr range
//
// swagger:model AddrRange
type AddrRange struct {

	// end
	End string `json:"End,omitempty"`

	// start
	Start string `json:"Start,omitempty"`
}

// Validate validates this addr range
func (m *AddrRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this addr range based on context it is used
func (m *AddrRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddrRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddrRange) UnmarshalBinary(b []byte) error {
	var res AddrRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
