// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LocalAddressSpecTiny local address spec tiny
//
// swagger:model LocalAddressSpecTiny
type LocalAddressSpecTiny struct {

	// addr
	Addr string `json:"addr,omitempty"`

	// device
	Device string `json:"device,omitempty"`
}

// Validate validates this local address spec tiny
func (m *LocalAddressSpecTiny) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this local address spec tiny based on context it is used
func (m *LocalAddressSpecTiny) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LocalAddressSpecTiny) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LocalAddressSpecTiny) UnmarshalBinary(b []byte) error {
	var res LocalAddressSpecTiny
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
