// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerStats server stats
//
// swagger:model ServerStats
type ServerStats struct {

	// conns
	Conns uint64 `json:"Conns,omitempty"`

	// cps
	Cps uint32 `json:"Cps,omitempty"`

	// in bps
	InBps uint32 `json:"InBps,omitempty"`

	// in bytes
	InBytes uint64 `json:"InBytes,omitempty"`

	// in pkts
	InPkts uint64 `json:"InPkts,omitempty"`

	// in pps
	InPps uint32 `json:"InPps,omitempty"`

	// out bps
	OutBps uint32 `json:"OutBps,omitempty"`

	// out bytes
	OutBytes uint64 `json:"OutBytes,omitempty"`

	// out pkts
	OutPkts uint64 `json:"OutPkts,omitempty"`

	// out pps
	OutPps uint32 `json:"OutPps,omitempty"`
}

// Validate validates this server stats
func (m *ServerStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server stats based on context it is used
func (m *ServerStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerStats) UnmarshalBinary(b []byte) error {
	var res ServerStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
