// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VsAnnouncePort vs announce port
//
// swagger:model VsAnnouncePort
type VsAnnouncePort struct {

	// dpvs
	Dpvs string `json:"dpvs,omitempty"`

	// switch
	Switch string `json:"switch,omitempty"`
}

// Validate validates this vs announce port
func (m *VsAnnouncePort) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vs announce port based on context it is used
func (m *VsAnnouncePort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VsAnnouncePort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VsAnnouncePort) UnmarshalBinary(b []byte) error {
	var res VsAnnouncePort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
