#!/bin/sh -
# program: dpvs
# Aug 28, 2019
# Commit: f393fa75e62639c1591f7157588d14630a653069
#         "ctrl: serveral improvements and bugfix in dpvs_msg"
# Features: 
#     bugfix in dpvs_msg and dpvs_timer

export VERSION=1.7
export RELEASE=6

echo $VERSION-$RELEASE
