name: Build

on:
  push:
    branches: [master, devel, DPVS-1.8-LTS]
  release:
    branches: [master]
    types: [published]
  schedule:
    - cron:  '30 2 * * 1'
  pull_request:
    branches: [master, devel, DPVS-1.8-LTS]
    types: [labeled]

jobs:
  build-basic:
    runs-on: self-hosted
    env:
      PKG_CONFIG_PATH: /data/dpdk/dpdklib/lib64/pkgconfig
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: build
      run: make -j
      
  build-all:
    runs-on: self-hosted
    env:
      PKG_CONFIG_PATH: /data/dpdk/dpdklib/lib64/pkgconfig
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Config
      run: sed -i 's/=n$/=y/' config.mk
    - name: build
      run: make -j
