name: Build

on:
  push:
    branches: [master, devel]
  release:
    branches: [master]
    types: [published]
  schedule:
    - cron:  '30 2 * * 1'
  pull_request:
    branches: [master, devel]
    types: [labeled]

jobs:
  build-basic:
    runs-on: self-hosted
    env:
      PKG_CONFIG_PATH: /data/dpdk/dpdklib/lib64/pkgconfig
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j
      
  build-debug:
    runs-on: self-hosted
    env:
      PKG_CONFIG_PATH: /data/dpdk/dpdklib/lib64/pkgconfig
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: sed -i 's/#CFLAGS +=/CFLAGS +=/' src/config.mk && sed -i 's/^#DEBUG := 1/DEBUG := 1/' src/Makefile
    - name: make
      run: make -j
