name: RUN-LTS

on:
  push:
    branches:
      - 'DPVS-1.9-LTS'
  release:
    branches:
      - 'DPVS-1.9-LTS'
    types:
      - published
  pull_request:
    types:
      - labeled
    branches:
      - 'DPVS-1.9-LTS'

jobs:
  run-dpvs:
    runs-on: self-hosted
    env:
      PKG_CONFIG_PATH: /data/dpdk/20.11.10/dpdklib/lib64/pkgconfig
      #ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build
      run: make -j
    - name: Install
      run: make install
    - name: Run DPVS
      run: sudo dpvsci $(pwd)/bin/dpvs
