name: Run

on:
  push:
    branches: [master, devel, DPVS-1.8-LTS]
  release:
    branches: [master]
    types: [published]
  schedule:
    - cron:  '30 3 * * 1'
  pull_request:
    branches: [master, devel, DPVS-1.8-LTS]
    types: [labeled]

jobs:
  run-dpvs:
    runs-on: self-hosted
    env:
      PKG_CONFIG_PATH: /data/dpdk/dpdklib/lib64/pkgconfig
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Build
      run: make -j
    - name: Install
      run: make install
    - name: Run DPVS
      run: sudo dpvsci $(pwd)/bin/dpvs
